# Generated by Django 5.0.3 on 2024-03-20 20:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_alter_userchoice_chosen_activity_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userchoice',
            old_name='chosen_activity',
            new_name='recommendations',
        ),
    ]
