# Generated by Django 5.0.3 on 2024-03-19 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0003_customuser_delete_user_alter_userchoice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='tags',
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.customuser'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weatherapp.customuser'),
        ),
        migrations.AddField(
            model_name='customuser',
            name='tags',
            field=models.ManyToManyField(to='weatherapp.userprofile'),
        ),
    ]
