# Generated by Django 5.0.3 on 2024-03-19 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_remove_customuser_tags_alter_userchoice_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='history',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='tags',
        ),
    ]
