# Generated by Django 5.0.3 on 2024-03-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0004_rename_chosen_activity_userchoice_recommendations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchoice',
            name='recommendations',
            field=models.TextField(),
        ),
    ]
