# Generated by Django 5.0.3 on 2024-03-19 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0005_remove_customuser_history_remove_customuser_tags'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userchoice',
            name='activity_chosen',
        ),
        migrations.AddField(
            model_name='userchoice',
            name='chosen_activity',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AddField(
            model_name='userchoice',
            name='chosen_city',
            field=models.CharField(default=None, max_length=25),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='userchoice',
            name='weather',
            field=models.CharField(max_length=25),
        ),
    ]
