# Generated by Django 5.0.3 on 2024-03-21 05:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weatherapp', '0012_remove_userchoice_recommendations_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recommendationchoice',
            old_name='district',
            new_name='city',
        ),
    ]
